filegroup(
    name = "data",
    srcs = [
        "enwiki-20220401-pages-articles-multistream-index1.txt-p1p41242",
        "enwiki-20220401-pages-articles-multistream-index1.txt-p1p41242.bz2",
        "enwiki-20220401-pages-articles-multistream1.xml-p1p41242.bz2",
        "enwiki-20220420-pages-articles-multistream.xml.bz2",
        "enwiki-20220420-pages-articles-multistream-index.txt",
    ],
    visibility = ["//visibility:public"],
)
